DROP TABLE `waz_options`;

CREATE TABLE `waz_options` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `opt_libelle` TEXT default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `waz_options` (`opt_libelle`) VALUES ("dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet"),("facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum"),("Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum"),("enim"),("Etiam laoreet, libero et tristique pellentesque, tellus"),("luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl"),("enim. Nunc ut erat. Sed"),("eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non"),("felis purus ac tellus. Suspendisse sed dolor."),("ipsum.");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("ac sem ut dolor"),("tempor, est ac"),("a feugiat"),("Class aptent taciti sociosqu ad litora"),("sed libero. Proin sed turpis nec"),("Cras lorem lorem,"),("leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante"),("laoreet, libero et"),("venenatis vel, faucibus"),("odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed"),("sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed"),("vulputate velit eu"),("eget tincidunt dui"),("sem"),("facilisis non, bibendum sed, est. Nunc laoreet lectus"),("dapibus id, blandit at, nisi. Cum sociis natoque"),("mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id"),("et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque"),("magnis dis parturient");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel,"),("dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor."),("pede. Cras vulputate velit eu sem. Pellentesque"),("tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis"),("id"),("erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed"),("id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at,"),("et pede. Nunc sed"),("Cras pellentesque. Sed dictum."),("amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus,");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus"),("Donec est mauris, rhoncus id,"),("Maecenas"),("Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa"),("torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In"),("sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin"),("arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit"),("eu neque pellentesque massa lobortis"),("iaculis nec,"),("mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim"),("felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc"),("cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus."),("nunc, ullamcorper eu, euismod ac, fermentum vel, mauris."),("magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero"),("augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu"),("vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris."),("ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat"),("Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam."),("faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("fermentum metus. Aenean sed pede nec"),("In lorem. Donec elementum, lorem ut aliquam"),("fermentum metus. Aenean sed"),("orci, in"),("condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede."),("Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus"),("non, egestas a, dui. Cras pellentesque. Sed dictum. Proin"),("turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque"),("mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus"),("vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit,");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("Nullam enim. Sed nulla ante, iaculis"),("vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat"),("eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada"),("Curabitur"),("eleifend, nunc risus varius"),("eleifend egestas. Sed pharetra, felis eget"),("a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam"),("elit. Aliquam auctor, velit eget laoreet"),("id risus quis diam luctus lobortis. Class aptent taciti"),("adipiscing");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin"),("natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque"),("erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi"),("consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus"),("natoque penatibus et magnis dis parturient"),("dui. Fusce aliquam, enim"),("facilisis eget, ipsum."),("Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis"),("mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum."),("lacinia");
INSERT INTO `waz_options` (`opt_libelle`) VALUES ("sed, hendrerit"),("mi felis, adipiscing"),("Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget"),("sem semper"),("morbi tristique"),("a nunc. In at pede. Cras vulputate velit"),("luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class"),("vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,"),("Proin"),("Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis.");
